/**
 * Product SKU helpers.
 *
 * SKUs are generated by the database (trigger on `products`), never by the client.
 * These helpers exist purely for display / validation in the admin UI.
 *
 * Format: `PRD|SVC - CITY(3) - CAT(3) - NAME(<=6) - SUFFIX(3)`
 *   e.g. PRD-BEN-APP-DRVCOV-7K2   SVC-GLB-BAY-SINGLE-H5Y
 * `GLB` is used for global (no city) items.
 */

export const GENERATED_SKU_PATTERN =
  /^(PRD|SVC)-[A-Z]{1,3}-[A-Z0-9]{1,3}-[A-Z0-9]{1,6}-[A-Z0-9]{3}$/;

export interface ParsedSku {
  kind: "product" | "service";
  city: string;
  category: string;
  name: string;
  suffix: string;
  isGlobal: boolean;
}

/** True when the SKU follows the system-generated format. */
export function isGeneratedSku(sku: string | null | undefined): boolean {
  return !!sku && GENERATED_SKU_PATTERN.test(sku.trim());
}

/** Splits a generated SKU into its segments. Returns null for legacy/free-form codes. */
export function parseProductSku(sku: string | null | undefined): ParsedSku | null {
  if (!isGeneratedSku(sku)) return null;
  const [prefix, city, category, name, suffix] = sku!.trim().split("-");
  return {
    kind: prefix === "SVC" ? "service" : "product",
    city,
    category,
    name,
    suffix,
    isGlobal: city === "GLB",
  };
}

/**
 * Preview of the SKU the database will assign. Display-only — the authoritative
 * value (including the unique suffix) always comes back from the server.
 */
export function previewSkuBase(input: {
  item_type?: string | null;
  city?: string | null;
  category?: string | null;
  name?: string | null;
}): string {
  const seg = (raw: string | null | undefined, len: number, fallback: string, alnum = true) => {
    const cleaned = (raw ?? "")
      .replace(alnum ? /[^A-Za-z0-9]/g : /[^A-Za-z]/g, "")
      .toUpperCase()
      .slice(0, len);
    return cleaned || fallback;
  };
  const prefix = (input.item_type ?? "product").toLowerCase() === "service" ? "SVC" : "PRD";
  const city = seg(input.city, 3, "GLB", false);
  const category = seg(input.category, 3, "OTH");
  const name = seg(input.name, 6, "ITEM");
  return `${prefix}-${city}-${category}-${name}`;
}
